version: "3.6"
services:
  deluge:
    networks:
      - default
    ports:
      - "8112:8112"
    image: linuxserver/deluge:latest
    restart: unless-stopped
    volumes:
      - /mnt/localfs/deluge:/config
      - /mnt/downloads:/downloads
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
      - UMASK=022
      - DELUGE_LOGLEVEL=error
  sonarr:
    networks:
      - default
    ports:
      - "8989:8989"
    image: linuxserver/sonarr:develop
    restart: unless-stopped
    volumes:
      - /mnt/localfs/sonarr:/config
      - /mnt/downloads:/downloads
      - /mnt/tv:/tv
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
      - UMASK_SET=022
  radarr:
    networks:
      - default
    ports:
      - "7878:7878"
    image: linuxserver/radarr:nightly
    restart: unless-stopped
    volumes:
      - /mnt/localfs/radarr:/config
      - /mnt/downloads:/downloads
      - /mnt/movies:/movies
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
      - UMASK_SET=022
  bazarr:
    networks:
      - default
    ports:
      - "6767:6767"
    image: linuxserver/bazarr:development
    restart: unless-stopped
    volumes:
      - /mnt/localfs/bazarr:/config
      - /mnt/downloads:/downloads
      - /mnt/movies:/movies
      - /mnt/tv:/tv
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
      - UMASK_SET=022
  prowlarr:
    networks:
      - default
    ports:
      - "9696:9696"
    image: linuxserver/prowlarr:nightly
    restart: unless-stopped
    volumes:
      - /mnt/localfs/prowlarr:/config
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
