version: "3.6"
services:
  duplicati:
    networks:
      - web_web
    image: ghcr.io/linuxserver/duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/localfs/duplicati:/config
      - /mnt/george/containers:/backups
      - /mnt/localfs:/localfs
    restart: unless-stopped
  synapse:
    networks:
      - web_web
    ports:
      - "8008:8008"
    image: matrixdotorg/synapse:latest
    environment:
      - UID=0
      - GID=0
      - TZ=Europe/London
    volumes:
      - /mnt/localfs/synapse:/data
    restart: unless-stopped
  synapsebot:
    networks:
      - web_web
    image: matrixdotorg/go-neb:latest
    ports:
      - "4050:4050"
    environment:
      - BIND_ADDRESS=:4050
      - DATABASE_TYPE=sqlite3
      - DATABASE_URL=/data/go-neb.db?_busy_timeout=5000
      - BASE_URL=https://bot.duffle.one
    volumes:
      - /mnt/localfs/synapsebot:/data
networks:
  web_web:
    external: true
