version: "3.6"
services:
  duplicati:
    ports:
     - "8200:8200"
    image: ghcr.io/linuxserver/duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/localfs/duplicati:/config
      - /mnt/laura/containers:/backups
      - /mnt/localfs:/localfs
    restart: unless-stopped
