version: "3.6"
services:
  duplicati:
    networks:
      - web_web
    image: ghcr.io/linuxserver/duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/localfs/duplicati:/config
      - /mnt/george/containers:/backups
      - /mnt/localfs:/localfs
    restart: unless-stopped
  synapse:
    networks:
      - web_web
    ports:
      - "8008:8008"
    image: matrixdotorg/synapse:latest
    environment:
      - UID=0
      - GID=0
      - TZ=Europe/London
    volumes:
      - /mnt/localfs/synapse:/data
    restart: unless-stopped
networks:
  web_web:
    external: true
