version: "3.6"
services:
  duplicati:
    networks:
      - web_web
    image: ghcr.io/linuxserver/duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/localfs/duplicati:/config
      - /mnt/george/containers:/backups
      - /mnt/localfs:/localfs
    restart: unless-stopped
networks:
  web_web:
    external: true
