version: "3.6"
services:
  caddy:
    ports:
      - "443:443"
      - "80:80"
    image: duffleman/caddy:2
    restart: unless-stopped
    volumes:
      - /mnt/caddy/config:/config
      - /mnt/caddy/data:/data
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    command:
      [
        "caddy",
        "run",
        "--config",
        "/config/Caddyfile",
        "--adapter",
        "caddyfile",
      ]
  ombi:
    image: linuxserver/ombi:development
    restart: unless-stopped
    volumes:
      - /mnt/localfs/ombi:/config
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
  deluge:
    ports:
      - "8112:8112"
    image: linuxserver/deluge:latest
    restart: unless-stopped
    volumes:
      - /mnt/localfs/deluge:/config
      - /mnt/downloads:/downloads
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
      - UMASK=022
      - DELUGE_LOGLEVEL=error
  sonarr:
    ports:
      - "8989:8989"
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    volumes:
      - /mnt/localfs/sonarr:/config
      - /mnt/downloads:/downloads
      - /mnt/tv-a1:/tv-a1
      - /mnt/tv-a2:/tv-a2
      - /mnt/tv-a3:/tv-a3
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
      - UMASK_SET=022
  radarr:
    ports:
      - "7878:7878"
    image: linuxserver/radarr:nightly
    restart: unless-stopped
    volumes:
      - /mnt/localfs/radarr:/config
      - /mnt/downloads:/downloads
      - /mnt/movies-a2:/movies-a2
      - /mnt/movies-a3:/movies-a3
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
      - UMASK_SET=022
  bazarr:
    ports:
      - "6767:6767"
    image: linuxserver/bazarr:development
    restart: unless-stopped
    volumes:
      - /mnt/localfs/bazarr:/config
      - /mnt/downloads:/downloads
      - /mnt/movies-a2:/movies-a2
      - /mnt/movies-a3:/movies-a3
      - /mnt/tv-a1:/tv-a1
      - /mnt/tv-a2:/tv-a2
      - /mnt/tv-a3:/tv-a3
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
      - UMASK_SET=022
  jackett:
    ports:
      - "9117:9117"
    image: linuxserver/jackett:latest
    restart: unless-stopped
    volumes:
      - /mnt/localfs/jackett:/config
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
