version: "3.6"
services:
  caddy:
    networks:
      - default
      - web
    ports:
      - "443:443"
      - "80:80"
    image: duffleman/caddy:2
    restart: unless-stopped
    volumes:
      - /mnt/caddy/config:/config
      - /mnt/caddy/data:/data
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    command:
      [
        "caddy",
        "run",
        "--config",
        "/config/Caddyfile",
        "--adapter",
        "caddyfile",
      ]
networks:
  web:
    driver: overlay
