apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      nodeSelector:
        dfl.mn/datacentre: digitalocean
      volumes:
      - name: heimdall-env
        secret:
          secretName: heimdall
          items:
          - key: env
            path: env
      containers:
        - name: heimdall
          image: linuxserver/heimdall:latest
          volumeMounts:
          - name: heimdall-env
            mountPath: /k8s-config
          ports:
          - containerPort: 80
          env:
            - name: TZ
              value: Europe/London
