apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-jackett
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/auth-tls-secret: 'default/secret-jackett'
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - jackett.i.dfl.mn
    secretName: secret-jackett
  rules:
  - host: jackett.i.dfl.mn
    http:
      paths:
      - path: /
        backend:
          serviceName: jackett
          servicePort: 9117
