apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nas-downloads
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.254.60
    path: '/mnt/array3/Downloads'
