apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-a3
  annotations:
    volume.beta.kubernetes.io/mount-options: "noacl,nocto,noatime,nodiratime"
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.254.60
    path: '/mnt/array3/Movies'
