apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tv-a3
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.254.60
    path: '/mnt/array3/Television'
