apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tv-a3
spec:
  resources:
    requests:
      storage: 100Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-tv-a3
