apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
  labels:
    app: ombi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ombi
  template:
    metadata:
      labels:
        app: ombi
    spec:
      nodeSelector:
        dfl.mn/datacentre: mission
      containers:
        - name: ombi
          image: linuxserver/ombi:latest
          ports:
          - containerPort: 3579
          volumeMounts:
          - mountPath: /config
            name: antfarm
          env:
          - name: PUID
            valueFrom:
              configMapKeyRef:
                name: configmap-linuxserver
                key: puid
          - name: PGID
            valueFrom:
              configMapKeyRef:
                name: configmap-linuxserver
                key: pgid
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: configmap-linuxserver
                key: timezone
      volumes:
        - name: antfarm
          persistentVolumeClaim:
            claimName: pvc-localfs-ombi
