apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      nodeSelector:
        dfl.mn/datacentre: mission
      containers:
        - name: radarr
          image: linuxserver/radarr:preview
          ports:
          - containerPort: 7878
          volumeMounts:
          - mountPath: /downloads
            name: downloads
          - mountPath: /config
            name: antfarm
          - mountPath: /movies-a2
            name: movies-a2
          - mountPath: /movies-a3
            name: movies-a3
          env:
          - name: PUID
            valueFrom:
              configMapKeyRef:
                name: configmap-linuxserver
                key: puid
          - name: PGID
            valueFrom:
              configMapKeyRef:
                name: configmap-linuxserver
                key: pgid
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: configmap-linuxserver
                key: timezone
          - name: UMASK_SET
            valueFrom:
              configMapKeyRef:
                name: configmap-linuxserver
                key: umask
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: pvc-downloads
        - name: antfarm
          persistentVolumeClaim:
            claimName: pvc-localfs-radarr
        - name: movies-a2
          persistentVolumeClaim:
            claimName: pvc-movies-a2
        - name: movies-a3
          persistentVolumeClaim:
            claimName: pvc-movies-a3
