apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-antfarm-radarr
spec:
  resources:
    requests:
      storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-antfarm-radarr
