apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: issuer-cert-manager-production
spec:
  acme:
    email: security@duffleman.co.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-production
    solvers:
    - selector:
        dnsZones:
        - 'do.dfl.mn'
      dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean
            key: personal-token
    - selector:
        dnsZones:
        - 'dfl.mn'
        - 'georgeflix.uk'
      dns01:
        cloudflare:
          email: cloudflare@duffleman.co.uk
          apiTokenSecretRef:
            name: cloudflare
            key: api-token
