apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  labels:
    app: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      nodeSelector:
        dfl.mn/datacentre: mission
      containers:
        - name: deluge
          image: linuxserver/deluge:latest
          ports:
          - containerPort: 8112
          volumeMounts:
          - mountPath: /downloads
            name: downloads
          - mountPath: /config
            name: antfarm
          env:
          - name: PUID
            valueFrom:
              configMapKeyRef:
                name: configmap-linuxserver
                key: puid
          - name: PGID
            valueFrom:
              configMapKeyRef:
                name: configmap-linuxserver
                key: pgid
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: configmap-linuxserver
                key: timezone
          - name: UMASK_SET
            valueFrom:
              configMapKeyRef:
                name: configmap-linuxserver
                key: umask
          - name: DELUGE_LOGLEVEL
            value: error
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: pvc-downloads
        - name: antfarm
          persistentVolumeClaim:
            claimName: pvc-antfarm-deluge
