apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nas-antfarm-deluge
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.254.60
    path: '/mnt/array2/antfarm/deluge'
