apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-localfs-deluge
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  volumeName: pv-localfs-deluge
