apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-antfarm-sonarr
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.254.60
    path: '/mnt/array2/antfarm/sonarr'
