apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localfs-sonarr
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  volumeName: localfs-sonarr
