apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-a2
spec:
  resources:
    requests:
      storage: 100Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: movies-a2
