apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  resources:
    requests:
      storage: 100Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: downloads
