apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: issuer-cert-manager-production
spec:
  tls:
    - hosts:
        - api.duffle.one
      secretName: cert-dflapi
  rules:
    - host: api.duffle.one
      http:
        paths:
          - path: /1/auth
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ghcr.io/duffleone/dfl:sha-22dbbab
          args: ["auth"]
          ports:
            - containerPort: 80
          env:
            - name: ENV
              value: prod
            - name: AUTH_SERVER_ADDR
              value: "0.0.0.0:80"
            - name: AUTH_SERVER_GRACEFUL
              value: "5"
            - name: AUTH_LOGGING_FORMAT
              value: "json"
            - name: AUTH_JWT_ISSUER
              value: auth.duffle.one
            - name: AUTH_WEBAUTHN_RPID
              value: auth.duffle.one
            - name: AUTH_WEBAUTHN_RPORIGIN
              value: https://auth.duffle.one
            - name: AUTH_WEBAUTHN_RPDISPLAYNAME
              value: DFL Auth
            - name: AUTH_DSN
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: dsn
            - name: AUTH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: public
            - name: AUTH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: private
