apiVersion: apps/v1
kind: Deployment
metadata:
  name: dflmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dflmon
  template:
    metadata:
      labels:
        app: dflmon
    spec:
      volumes:
      - name: dflmon
        configMap:
          name: dflmon
      containers:
        - name: dflmon
          image: duffleman/dflmon:latest
          volumeMounts:
          - name: dflmon
            mountPath: /dflmon_config
          env:
          - name: ADDR
            value: :80
          - name: DFLMON_CACHET_TOKEN
            valueFrom:
              secretKeyRef:
                name: dflmon
                key: cachet-token
          - name: DFLMON_DEBUG
            value: 'false'
          - name: DFLMON_CACHET_URL
            value: 'http://cachet:8000'
          - name: DFLMON_CONFIG
            value: '/dflmon_config/config'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dflmon
data:
  config: |
    {
      "jobs": [
        {
          "name": "plex",
          "component_name": "PLEX Server",
          "type": "https-novalidate",
          "host": "galactus.ext.dfl.mn:32400/web/index.html",
          "interval": 120
        },
        {
          "name": "ombi",
          "component_name": "Ombi",
          "type": "https",
          "host": "requests.georgeflix.uk",
          "interval": 120
        },
        {
          "name": "synclongue",
          "component_name": "Synclounge",
          "type": "https",
          "host": "sync.georgeflix.uk",
          "interval": 120
        }
      ]
    }
