apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nextcloud
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: issuer-cert-manager-production
spec:
  tls:
    - hosts:
        - cloud.dfl.mn
      secretName: cert-nextcloud
  rules:
    - host: cloud.dfl.mn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-store
          persistentVolumeClaim:
            claimName: csi-pvc-nextcloud
      containers:
        - name: nextcloud
          image: nextcloud:18.0.12-apache
          volumeMounts:
            - mountPath: "/var/www/html/"
              name: nextcloud-store
          ports:
            - containerPort: 80
          env:
          - name: POSTGRES_USER
            value: nextcloud
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud
                key: db-password
          - name: POSTGRES_HOST
            value: 'db-postgresql-lon1-17763-do-user-308239-0.a.db.ondigitalocean.com:25060/nextcloud?sslmode=require'
          - name: NEXTCLOUD_ADMIN_USER
            value: Duffleman
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud
                key: password
          - name: NEXTCLOUD_DATA_DIR
            value: /var/www/html/data
          - name: NEXTCLOUD_TRUSTED_DOMAINS
            value: 'duffleman.co.uk dfl.mn cloud.dfl.mn'
          - name: REDIS_HOST
            value: 'private-db-redis-lon1-75276-do-user-6285334-0.a.db.ondigitalocean.com'
          - name: REDIS_HOST_PORT
            value: '25061'
          - name: REDIS_HOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud
                key: redis-password
          - name: OVERWRITEHOST
            value: cloud.dfl.mn
          - name: OVERWRITEPROTOCOL
            value: https
          - name: OVERWRITEWEBROOT
            value: /
