apiVersion: v1
kind: Service
metadata:
  name: short
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: short
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: short
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: issuer-cert-manager-production
spec:
  tls:
    - hosts:
      - dfl.mn
      secretName: cert-short
  rules:
  - host: dfl.mn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: short
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: short
spec:
  replicas: 1
  selector:
    matchLabels:
      app: short
  template:
    metadata:
      labels:
        app: short
    spec:
      containers:
        - name: short
          image: duffleman/dfl:latest
          args: ["short"]
          ports:
          - containerPort: 80
          env:
          - name: SHORT_PORT
            value: '80'
          - name: SHORT_AWS_REGION
            value: eu-west-1
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: short
                key: aws-access-key
          - name: AWS_DEFAULT_REGION
            value: eu-west-1
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: short
                key: aws-secret-key
          - name: SHORT_ROOT_URL
            value: https://dfl.mn
          - name: SHORT_SALT
            valueFrom:
              secretKeyRef:
                name: short
                key: salt
          - name: SHORT_USERS
            valueFrom:
              secretKeyRef:
                name: short
                key: users
          - name: SHORT_DSN
            valueFrom:
              secretKeyRef:
                name: short
                key: dsn
          - name: SHORT_REDIS_URI
            valueFrom:
              secretKeyRef:
                name: short
                key: redis-uri
          - name: SHORT_STORAGE_PROVIDER
            value: aws
