apiVersion: v1
kind: Service
metadata:
  name: tflgame
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: tflgame
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tflgame
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: issuer-cert-manager-production
spec:
  tls:
    - hosts:
        - api.tflga.me
      secretName: cert-tflgame
  rules:
    - host: api.tflga.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tflgame
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tflgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tflgame
  template:
    metadata:
      labels:
        app: tflgame
    spec:
      containers:
        - name: tflgame
          image: duffleman/tflgame:cors
          ports:
            - containerPort: 80
          env:
            - name: CONFIG
              valueFrom:
                secretKeyRef:
                  name: tflgame
                  key: CONFIG
