apiVersion: v1
kind: Service
metadata:
  name: wiki
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: wiki
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wiki-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: issuer-cert-manager-production
spec:
  tls:
    - hosts:
      - wiki.dfl.mn
      secretName: cert-wiki
  rules:
  - host: wiki.dfl.mn
    http:
      paths:
      - backend:
          serviceName: wiki
          servicePort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
        - name: wiki
          image: requarks/wiki:2
          ports:
          - containerPort: 3000
          env:
          - name: PORT
            value: '3000'
          - name: DB_TYPE
            value: postgres
          - name: DB_HOST
            value: db-postgresql-lon1-17763-do-user-308239-0.a.db.ondigitalocean.com
          - name: DB_PORT
            value: '25061'
          - name: DB_USER
            value: wiki
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: wiki
                key: db-pass
          - name: DB_NAME
            value: 'wiki'
          - name: DB_SSL
            value: 'true'
          - name: DB_SSL_CA
            valueFrom:
              secretKeyRef:
                name: wiki
                key: db-cert
