apiVersion: v1
kind: ConfigMap
metadata:
  name: dflmon
data:
  config: |
    {
      "jobs": [
        {
          "name": "plex",
          "component_name": "PLEX Server",
          "type": "https-novalidate",
          "host": "galactus.int.dfl.mn:32400/web/index.html",
          "interval": 120
        },
        {
          "name": "vpn_tunnel",
          "component_name": "VPN Bridge",
          "type": "icmp",
          "host": "192.168.254.254",
          "interval": 120
        },
        {
          "name": "ombi",
          "component_name": "Ombi",
          "type": "https",
          "host": "requests.georgeflix.uk",
          "interval": 120
        },
        {
          "name": "deluge",
          "component_name": "Deluge",
          "type": "http",
          "host": "deluge:8112",
          "interval": 120
        },
        {
          "name": "sonarr",
          "component_name": "Sonarr",
          "type": "http",
          "host": "sonarr:8989",
          "interval": 120
        },
        {
          "name": "radarr",
          "component_name": "Radarr",
          "type": "http",
          "host": "radarr:7878",
          "interval": 120
        },
        {
          "name": "galactus",
          "component_name": "galactus",
          "type": "icmp",
          "host": "galactus.int.dfl.mn",
          "interval": 120
        }
      ]
    }
